# Generated by Django 4.0.4 on 2022-04-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notesapp', '0002_alter_employee_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('books', models.ManyToManyField(to='Notesapp.book')),
            ],
        ),
    ]
