# Generated by Django 4.0.4 on 2022-04-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notesapp', '0003_book_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAtomicityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_a', models.CharField(max_length=100)),
                ('user_b', models.CharField(max_length=100)),
            ],
        ),
    ]
