# Generated by Django 4.0.4 on 2022-04-27 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notesapp', '0004_transactionatomicitymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionatomicitymodel',
            old_name='user_a',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transactionatomicitymodel',
            old_name='user_b',
            new_name='user',
        ),
    ]
