# Generated by Django 4.0.4 on 2022-04-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notesapp', '0006_group_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
