# Generated by Django 4.0.4 on 2022-05-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notesapp', '0007_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('time_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
